#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into raulb/boom, for example.

case "$1" in
  "dotfiles")
    cd ~/.dotfiles
    ;;
  "hclm")
    cd ~/code/hclm/hclm-mobile
    ;;
  *)
    cd "$PROJECTS/$1"
    ;;
esac
