cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'meroxa/taps'
tap 'derailed/k9s'

brew 'libgit2'
brew 'openssl'
brew 'postgresql'
brew 'hyperkit'
brew 'minikube'
brew 'go'
brew 'direnv'
brew 'asdf'
brew 'meroxa'
cask 'httpie'
cask 'keycastr'
brew 'k9s'
brew 'rtx'

tap 'homebrew/cask-fonts'
cask 'font-fira-code'